"""Learning guidance, tool-call checks, and per-turn retry state."""

import hashlib
import json
import os
import re
import shlex
import threading
from pathlib import Path

from hermes_constants import get_hermes_home

from .compat import (
    current_write_origin,
    file_mutation_targets,
    mark_native_background_review_skill_read,
    resolve_native_file_path,
)

PRIVATE_KEY_RE = re.compile(r"-----BEGIN (?:[A-Z0-9]+ )*PRIVATE KEY-----")
_STATE_LIMIT = 256
_STATE_LOCK = threading.Lock()
_RECOVERY = {}
_READ_RECEIPTS = {}
_LANES = {}
_VIEW_GENERATION = 0
_STATE_SATURATED = False
_CURATOR_READ_COMMANDS = {
    "df",
    "du",
    "ls",
    "pwd",
    "readlink",
    "realpath",
    "sha256sum",
    "stat",
    "wc",
}

SKILL_OWNER_GUIDANCE = """Before a skill write, load `skill-governance` with native `skill_view`. Inspect the catalog with `skills_list` and the current owner with `skill_view`, including relevant linked files. If inspection is incomplete, make no write. Update the existing owner after satisfying native read-before-write. Create a skill only when inspection finds no current owner for that responsibility. Keep related but distinct responsibilities separate and link them instead of copying guidance."""

COHERENT_SKILL_CHANGE_GUIDANCE = """Keep a multi-file skill change coherent. If its owner and support files cannot all be updated, make no write."""

AUTONOMOUS_SKILL_RETRY_GUIDANCE = """After the first rejected skill write in an autonomous review, reread the same owner and exact file before one retry. Success or another rejection closes learning writes for that review. Do not switch owners or files to bypass a rejection."""

LEARNING_QUALITY_GUIDANCE = f"""Hermes Learn Policy: durable learning

Apply this policy only when considering a native `memory` or `skill_manage` write. A no-write result is valid.

Choose the durable owner before writing:

- USER stores stable user facts, preferences, communication style, and expectations.
- MEMORY stores stable agent or environment facts, conventions, and corrections. Use declarative facts, not commands to a future agent.
- A skill stores reusable procedures and decision methods. Keep active guidance portable. Put session evidence in a reference only when it has lasting diagnostic value.

Before a memory write, load `profile-memory-governance` with native `skill_view` and follow its admission and write workflow. Inspect the complete current USER or MEMORY content available to this turn. A replacement must preserve every unrelated clause verbatim. Use one native atomic memory batch when several entries change. If ownership, capacity, or exact preservation is uncertain, make no write.

{SKILL_OWNER_GUIDANCE}

{COHERENT_SKILL_CHANGE_GUIDANCE}

Do not save secrets, changing status, task history, completion claims, issue, PR, commit, or test records, duplicate meaning, misplaced procedures, or unnecessary machine paths. Leave project and runtime facts in their source, and past task state in session history."""

FOREGROUND_GUIDANCE = """Foreground lane

The user's current task remains primary. The current user message may support a USER write when `profile-memory-governance` admits it."""

BACKGROUND_GUIDANCE = f"""Automatic review lane

The review request is generated by Hermes, not written by the user. It cannot establish a USER fact. Neither can system prompts, plugin guidance, review instructions, skills, assistant messages, or tool results. A USER write needs explicit support from an earlier real user message in the inherited conversation or an independently verified authoritative source. Without that evidence, do not write USER.

{AUTONOMOUS_SKILL_RETRY_GUIDANCE} A rejected memory write closes learning writes for the review immediately."""

CURATOR_GUIDANCE = f"""Hermes Learn Policy: Curator lane

Curator may change skills only.

{SKILL_OWNER_GUIDANCE}

{COHERENT_SKILL_CHANGE_GUIDANCE}

{AUTONOMOUS_SKILL_RETRY_GUIDANCE}

Keep Curator's native rules for ownership, pins, archive and delete operations, and provenance. Use terminal only for approved read-only inspection commands. Use `skill_manage` for every durable change."""


def _purge_superseded_turns_locked(session_id, turn_id):
    """Remove older turns from one session without evicting other active turns."""
    global _STATE_SATURATED
    session_id, turn_id = str(session_id), str(turn_id)
    for mapping in (_LANES, _RECOVERY, _READ_RECEIPTS):
        for key in tuple(mapping):
            if key[0] == session_id and key[1] != turn_id:
                mapping.pop(key, None)
    _STATE_SATURATED = any(
        len(mapping) >= _STATE_LIMIT
        for mapping in (_LANES, _RECOVERY, _READ_RECEIPTS)
    )


def _bounded_store_locked(mapping, key, value):
    global _STATE_SATURATED
    if key not in mapping and len(mapping) >= _STATE_LIMIT:
        _STATE_SATURATED = True
        return False
    mapping[key] = value
    return True


def _remember_lane(session_id, turn_id, lane):
    if not session_id or not turn_id:
        return
    key = (str(session_id), str(turn_id))
    with _STATE_LOCK:
        _purge_superseded_turns_locked(*key)
        _bounded_store_locked(_LANES, key, lane)


def pre_llm_call(platform="", session_id="", turn_id="", **_):
    if str(platform).lower() == "curator":
        _remember_lane(session_id, turn_id, "curator")
        return {"context": CURATOR_GUIDANCE}
    if current_write_origin() == "background_review":
        _remember_lane(session_id, turn_id, "background_review")
        guidance = BACKGROUND_GUIDANCE
    else:
        _remember_lane(session_id, turn_id, "foreground")
        guidance = FOREGROUND_GUIDANCE
    return {"context": f"{LEARNING_QUALITY_GUIDANCE}\n\n{guidance}"}


def _digest(value):
    return hashlib.sha256(str(value or "").encode()).hexdigest()


def _turn_key(session_id, turn_id):
    if not session_id or not turn_id:
        return None
    return (str(session_id), str(turn_id))


def _owner_digest(args):
    return _digest(args.get("name")) if isinstance(args, dict) else _digest("")


def _target_label(args):
    if not isinstance(args, dict):
        return None
    action = str(args.get("action") or "")
    if action not in {"edit", "patch", "delete", "write_file", "remove_file"}:
        return None
    return str(args.get("file_path") or "SKILL.md")


def _receipt_key(session_id, turn_id, args):
    turn = _turn_key(session_id, turn_id)
    target = _target_label(args)
    if turn is None or target is None:
        return None
    return (*turn, _owner_digest(args), _digest(target))


def _recovery_target_digest(args):
    if not isinstance(args, dict):
        return _digest("SKILL.md")
    return _digest(args.get("file_path") or "SKILL.md")


def _autonomous_lane(session_id, turn_id):
    turn = _turn_key(session_id, turn_id)
    if turn is None:
        return False
    with _STATE_LOCK:
        lane = _LANES.get(turn)
    return lane in {"background_review", "curator"}


def _parse_skill_view_result(args, result):
    if not isinstance(args, dict):
        return None
    try:
        payload = json.loads(result) if isinstance(result, str) else result
    except Exception:
        return None
    if not isinstance(payload, dict) or payload.get("success") is not True:
        return None
    if str(payload.get("name") or "") != str(args.get("name") or ""):
        return None
    expected = str(args.get("file_path") or "SKILL.md")
    if args.get("file_path") and str(payload.get("file") or "") != expected:
        return None
    path = payload.get("_source_path")
    if path is None and expected == "SKILL.md":
        skill_dir = payload.get("skill_dir")
        if isinstance(skill_dir, str) and Path(skill_dir).is_absolute():
            path = str(Path(skill_dir) / "SKILL.md")
        elif isinstance(payload.get("path"), str) and Path(payload["path"]).is_absolute():
            path = payload["path"]
    if not isinstance(path, str) or not Path(path).is_absolute():
        return None
    return Path(path).resolve()


def _remember_view(session_id, turn_id, args, result):
    global _VIEW_GENERATION
    key = _receipt_key(session_id, turn_id, {
        "action": "patch",
        "name": args.get("name") if isinstance(args, dict) else "",
        "file_path": args.get("file_path") if isinstance(args, dict) else None,
    })
    path = _parse_skill_view_result(args, result)
    if key is None or path is None:
        return
    with _STATE_LOCK:
        _VIEW_GENERATION += 1
        _bounded_store_locked(_READ_RECEIPTS, key, (_VIEW_GENERATION, path))


def _remember_rejection(session_id, turn_id, tool_name, args):
    if not _autonomous_lane(session_id, turn_id):
        return
    turn = _turn_key(session_id, turn_id)
    if turn is None:
        return
    with _STATE_LOCK:
        if turn in _RECOVERY:
            _RECOVERY[turn]["closed"] = True
            return
        state = {
            "tool": str(tool_name),
            "owner": _owner_digest(args) if tool_name == "skill_manage" else None,
            "target": (
                _recovery_target_digest(args)
                if tool_name == "skill_manage"
                else None
            ),
            "rejected_generation": _VIEW_GENERATION,
            "consumed": False,
            "closed": tool_name != "skill_manage",
        }
        _bounded_store_locked(_RECOVERY, turn, state)


def post_tool_call(
    tool_name="",
    args=None,
    result=None,
    status="",
    session_id="",
    turn_id="",
    **_,
):
    args = args if isinstance(args, dict) else {}
    if tool_name == "skill_view" and status == "ok":
        _remember_view(session_id, turn_id, args, result)
    elif tool_name in {"skill_manage", "memory"} and status == "error":
        _remember_rejection(session_id, turn_id, tool_name, args)
    return None


def _curator_terminal_is_read_only(command):
    command = str(command or "")
    if any(
        marker in command
        for marker in ("\n", "\r", ";", "&", "||", "|", ">", "<", "`", "$(")
    ):
        return False
    try:
        tokens = shlex.split(command)
    except ValueError:
        return False
    if not tokens:
        return False
    executable = Path(tokens[0]).name
    if executable != tokens[0] or "/" in tokens[0] or "\\" in tokens[0]:
        return False
    return executable in _CURATOR_READ_COMMANDS


def _home():
    return Path(get_hermes_home())


def _direct_owner(path, home, task_id=""):
    candidate = resolve_native_file_path(path, task_id)
    lexical_home = Path(os.path.abspath(home))
    for target, root in (
        (candidate.resolve(), lexical_home.resolve()),
        (candidate, lexical_home),
    ):
        if target == root / "memories" / "MEMORY.md":
            return "memory(target='memory')"
        if target == root / "memories" / "USER.md":
            return "memory(target='user')"
        try:
            target.relative_to(root / "skills")
            return "skill_manage"
        except ValueError:
            pass
    return None


def _persisted_text(args):
    values = [
        value
        for key in ("content", "new_text", "file_content", "new_string")
        if isinstance((value := args.get(key)), str)
    ]
    for operation in args.get("operations") or []:
        if not isinstance(operation, dict):
            continue
        values.extend(
            value
            for key in ("content", "new_text")
            if isinstance((value := operation.get(key)), str)
        )
    return "\n".join(values)


def _pre_decision(tool_name, args, home, task_id=""):
    if tool_name in {"skill_manage", "memory"} and PRIVATE_KEY_RE.search(
        _persisted_text(args)
    ):
        return {
            "action": "block",
            "message": "learning-policy: private-key material cannot be saved",
        }

    if tool_name in {"write_file", "patch"}:
        for path in file_mutation_targets(tool_name, args):
            owner = _direct_owner(path, home, task_id)
            if owner:
                return {
                    "action": "block",
                    "message": (
                        "learning-policy: learning files must be changed through "
                        f"{owner}"
                    ),
                }
    return None


def pre_tool_call(
    tool_name="",
    args=None,
    home=None,
    session_id="",
    turn_id="",
    task_id="",
    **kwargs,
):
    args = args if isinstance(args, dict) else {}
    turn = _turn_key(session_id, turn_id)
    with _STATE_LOCK:
        lane = _LANES.get(turn) if turn is not None else None
        saturated = _STATE_SATURATED
    if (
        saturated
        and current_write_origin() == "background_review"
        and tool_name in {"skill_manage", "memory", "terminal"}
    ):
        return {
            "action": "block",
            "message": (
                "learning-policy: autonomous learning state is full; "
                "continue on a fresh turn"
            ),
        }
    if tool_name == "terminal" and lane == "curator":
        if not _curator_terminal_is_read_only(args.get("command")):
            return {
                "action": "block",
                "message": (
                    "learning-policy: Curator terminal access is read-only; "
                    "use skill_manage for skill changes"
                ),
            }
        return None
    if tool_name not in {"skill_manage", "memory", "write_file", "patch"}:
        return None

    receipt_path = None
    if tool_name == "skill_manage" and turn is not None:
        receipt_key = _receipt_key(session_id, turn_id, args)
        with _STATE_LOCK:
            receipt = _READ_RECEIPTS.get(receipt_key) if receipt_key is not None else None
            recovery = _RECOVERY.get(turn)
            if lane in {"background_review", "curator"} and recovery is not None:
                allowed = (
                    not recovery["closed"]
                    and not recovery["consumed"]
                    and recovery["tool"] == "skill_manage"
                    and recovery["owner"] == _owner_digest(args)
                    and recovery["target"] == _recovery_target_digest(args)
                    and receipt is not None
                    and receipt[0] > recovery["rejected_generation"]
                )
                if not allowed:
                    return {
                        "action": "block",
                        "message": (
                            "learning-policy: retry only the rejected skill file "
                            "after reading that exact file again"
                        ),
                    }
                recovery["consumed"] = True
                recovery["closed"] = True
            receipt_path = receipt[1] if receipt is not None else None
    elif tool_name == "memory" and turn is not None:
        with _STATE_LOCK:
            recovery = _RECOVERY.get(turn)
            if lane in {"background_review", "curator"} and recovery is not None:
                return {
                    "action": "block",
                    "message": (
                        "learning-policy: a prior learning rejection closed "
                        "writes for this review"
                    ),
                }

    if receipt_path is not None and lane in {"background_review", "curator"}:
        mark_native_background_review_skill_read(receipt_path)
    try:
        return _pre_decision(
            tool_name,
            args,
            Path(home or _home()),
            task_id=task_id,
        )
    except Exception:
        if tool_name in {"skill_manage", "memory"}:
            return {
                "action": "block",
                "message": "learning-policy: tool-call check failed; inspect the proposal before retrying",
            }
        return None
